<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>drone_scenario_runner</name>
  <version>0.1.0</version>
  <description>
    Repeatable mission flight for PX4 SITL drone in field_robots_lab Scene 3.
    Provides offboard waypoint navigation via px4_msgs and orchestrated launches
    integrating PX4 SITL, Micro-XRCE-DDS Agent, Gazebo world, and telemetry recorder.
  </description>

  <maintainer email="slepynina.eu@gmail.com">EugeSlepynina</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>px4_msgs</exec_depend>
  <exec_depend>python3-yaml</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
